DDCE-3601 - added scalafmt, scalastyle, updated deps, updated sbt, fi…
hmrc/home-office-immigration-status-stubs pull request #57
Opened 2023-01-10 16:08 UTC by frikit

…x all warnings

2023-01-10 16:09 UTC, frikit commented on app/uk/gov/hmrc/homeofficesettledstatusstubs/services/StubDataService.scala
> -    val _ :: product :: status :: expired =
scala 2.13 complain that this match is not exhaustive so I had to do it this way

2023-01-12 09:21 UTC, EdCope requested changes
Just a warning when using ./run_all_tests.sh to update to IntegrationTest/test format

2023-01-12 09:56 UTC, frikit commented
done @EdCope

2023-01-12 10:04 UTC, EdCope approved these changes

2023-01-12 10:04 UTC, merged